### ISSUE TITLE
[Compatibility Request] Doesn't play nice with Tidy5e Sheet

### ISSUE THREAD

**Issue by harrisog** [aquavitae/hide-item-value#1] opened 2022-12-01 21:46 UTC
The `Appraised` field and `Show Price` checkbox both appear twice in the sidebar when displayed with Tidy Sheet, and do not properly save edits.

**Comment by aquavitae** [comment] 2022-12-02 06:32
Thanks. Should be fixed. Ironically it was caused by a failed attempt to add compatibility with Tidy5e.

**Closed as completed by aquavitae** 2022-12-02 06:32 UTC
